all: forward_diff2 backward_diff2 central_diff2

forward_diff2: forward_diff2.c forward_diff2.h
	gcc forward_diff2.c forward_diff2.h utils.h -o forward_diff2

backward_diff2: backward_diff2.c backward_diff2.h
	gcc backward_diff2.c backward_diff2.h utils.h -o backward_diff2

central_diff2: central_diff2.c central_diff2.h
	gcc central_diff2.c central_diff2.h utils.h -o central_diff2
