all: trapezoidal simpsons_3rd simpsons_38s open_nc gauss_quadr romberg

trapezoidal: trapezoidal.c trapezoidal.h
	gcc trapezoidal.c trapezoidal.h -o trapezoidal

simpsons_3rd: simpsons_3rd.c simpsons_3rd.h
	gcc simpsons_3rd.c simpsons_3rd.h -o simpsons_3rd

simpsons_38s: simpsons_38s.c simpsons_38s.h
	gcc simpsons_38s.c simpsons_38s.h -o simpsons_38s

open_nc: open_nc.c open_nc.h
	gcc open_nc.c open_nc.h -o open_nc

gauss_quadr: gauss_quadr.c gauss_quadr.h
	gcc gauss_quadr.c gauss_quadr.h -o gauss_quadr

romberg: romberg.c romberg.h
	gcc romberg.c romberg.h -o romberg
